dist: trusty

language: c

sudo: required
compiler: gcc

before_install:
- sudo add-apt-repository ppa:rebuntu16/glade-3.19+-trusty -y
- sudo apt-get update -q
- sudo apt-get install -y libglib2.0-dev libgtk-3-dev python3 libcurl3 gettext pkg-config libircclient-dev libircclient1

script: 
- mkdir build
- ./configure --prefix=/usr/local --disable-debug
- make
- sudo make DESTDIR=/ install
